image: Ubuntu1804
stack: node 10
branches:
  only:
    - master
cache: node_modules
install:
  - yarn
build: off
build_script:
  - yarn run build
test_script:
  - yarn run lint && yarn test
deploy_script:
  - git config --global credential.helper store
  - git config --global Kittennik65959 AppVeyor
  - git config --global kittennik@gmail.com ci@appveyor.com
  - echo https://%GITHUB_TOKEN%:x-oauth-basic@github.com>%USERPROFILE%\.git-credentials
  - dos2unix %USERPROFILE%\.git-credentials
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose